services:
  # Your C# API
  api:
    build:
      context: .
      dockerfile: CloudTaskManager.Server/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  # The Local Cloud
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - LOCALSTACK_AUTH_TOKEN=token
      - SERVICES=s3,dynamodb
    volumes:
      - "./volume:/var/lib/localstack"
